import { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';

const HomePage: NextPage = () => {
  return (
    <div className='content'>
      <Head>
        <title>mealwise</title>
        <meta name='description' content='Meal planning app generated by create-next-app' />
      </Head>

      <main className='main'>
        <h1 className='main__title'>
          mealwise
        </h1>

        <ul>
          <li>
            <Link href="/recipes">
              Recipe Book
            </Link>
          </li>
          <li>
            <Link href="/planner">
              Meal Plan
            </Link>
          </li>
          <li>
            <Link href="/shopping-list">
              Shopping List
            </Link>
          </li>
        </ul>
      </main>
    </div>
  );
};

export default HomePage;
